export const variantStyles = {
  innovative: {
    wrapper: "min-h-full bg-black relative overflow-hidden",
    bg1: "absolute top-1/3 right-0 w-[500px] h-[500px] bg-violet-500/10 rounded-full blur-3xl",
    bg2: "absolute bottom-0 left-1/4 w-[500px] h-[500px] bg-indigo-500/10 rounded-full blur-3xl",
    inner: "relative max-w-5xl mx-auto px-8 short:px-4 py-20 short:py-6",
    title:
      "text-8xl short:text-3xl font-black mb-6 short:mb-2 text-transparent bg-clip-text bg-gradient-to-r from-violet-400 via-indigo-400 to-blue-400 text-center",
    subtitle: "text-2xl short:text-sm text-gray-400 font-light text-center mb-16 short:mb-4",
    rulerText: "text-muted-foreground/70",
    gridLine: "border-border/15",
    blockBg: (color: string) => `${color}12`,
    blockBorder: (color: string) => `3px solid ${color}`,
    nameColor: (color: string) => color,
    companyText: "text-muted-foreground",
    roleText: "text-muted-foreground/50",
    tagBg: (color: string) => `${color}15`,
    tagText: (color: string) => `${color}99`,
    dateLabelText: "text-muted-foreground/40",
    durationColor: (color: string) => `${color}80`,
    educationBg: "bg-black border border-gray-800 rounded-2xl p-6",
    educationGrad: "bg-gradient-to-r from-blue-500 to-cyan-500",
    educationTitle: "text-xl font-black text-white",
    educationSub: "text-gray-500",
    // modal
    overlayBg: "bg-black/80 backdrop-blur-sm",
    modalBg: "bg-gray-950 border border-gray-800",
    modalTitle: "text-white",
    modalCompany: (color: string) => color,
    modalMeta: "text-gray-400",
    modalSectionTitle: "text-gray-500",
    modalText: "text-gray-300",
    modalTagBg: (color: string) => `${color}18`,
    modalTagText: (color: string) => color,
    modalBulletColor: (color: string) => color,
    parallelRowBg: (color: string) => `${color}08`,
    parallelBarColor: (color: string) => color,
    parallelName: (color: string) => color,
    parallelCompany: "text-muted-foreground",
  },
  professional: {
    wrapper: "min-h-full bg-white",
    bg1: "",
    bg2: "",
    inner: "max-w-4xl mx-auto px-8 short:px-4 py-24 short:py-8",
    title: "text-5xl short:text-2xl font-serif font-bold text-gray-900 mb-3 short:mb-1 text-left",
    subtitle:
      "text-xl short:text-sm text-gray-600 text-left mb-16 short:mb-4 pb-8 short:pb-4 border-b border-gray-200",
    rulerText: "text-gray-400",
    gridLine: "border-gray-200/40",
    blockBg: (color: string) => `${color}08`,
    blockBorder: (color: string) => `3px solid ${color}`,
    nameColor: (color: string) => color,
    companyText: "text-gray-600",
    roleText: "text-gray-400",
    tagBg: (color: string) => `${color}08`,
    tagText: (color: string) => `${color}aa`,
    dateLabelText: "text-gray-400",
    durationColor: (color: string) => `${color}80`,
    educationBg: "border-t border-gray-200 pt-8 mt-8",
    educationGrad: "",
    educationTitle: "text-xl font-bold text-gray-900",
    educationSub: "text-gray-600",
    overlayBg: "bg-black/40",
    modalBg: "bg-white border border-gray-200 shadow-2xl",
    modalTitle: "text-gray-900",
    modalCompany: (_color: string) => "#6b7280",
    modalMeta: "text-gray-600",
    modalSectionTitle: "text-gray-500",
    modalText: "text-gray-700",
    modalTagBg: (color: string) => `${color}10`,
    modalTagText: (color: string) => `${color}cc`,
    modalBulletColor: (color: string) => color,
    parallelRowBg: (color: string) => `${color}06`,
    parallelBarColor: (color: string) => color,
    parallelName: (color: string) => color,
    parallelCompany: "text-gray-500",
  },
  modern: {
    wrapper: "min-h-full bg-gradient-to-br from-slate-950 via-slate-900 to-slate-950",
    bg1: "",
    bg2: "",
    inner: "max-w-5xl mx-auto px-8 short:px-4 py-16 short:py-6",
    title:
      "text-5xl short:text-2xl font-bold mb-4 short:mb-2 bg-gradient-to-r from-blue-400 to-purple-400 bg-clip-text text-transparent text-center",
    subtitle: "text-xl short:text-sm text-slate-400 text-center mb-12 short:mb-4",
    rulerText: "text-slate-500",
    gridLine: "border-slate-800/50",
    blockBg: (color: string) => `${color}12`,
    blockBorder: (color: string) => `3px solid ${color}`,
    nameColor: (color: string) => color,
    companyText: "text-slate-400",
    roleText: "text-slate-500",
    tagBg: (color: string) => `${color}15`,
    tagText: (color: string) => `${color}99`,
    dateLabelText: "text-slate-500",
    durationColor: (color: string) => `${color}80`,
    educationBg: "bg-slate-900/50 border border-slate-800 rounded-xl p-6 backdrop-blur",
    educationGrad: "",
    educationTitle: "text-xl font-bold text-white",
    educationSub: "text-slate-400",
    overlayBg: "bg-black/70 backdrop-blur-sm",
    modalBg: "bg-slate-950 border border-slate-800 shadow-2xl",
    modalTitle: "text-white",
    modalCompany: (color: string) => color,
    modalMeta: "text-slate-400",
    modalSectionTitle: "text-slate-500",
    modalText: "text-slate-300",
    modalTagBg: (color: string) => `${color}18`,
    modalTagText: (color: string) => color,
    modalBulletColor: (color: string) => color,
    parallelRowBg: (color: string) => `${color}08`,
    parallelBarColor: (color: string) => color,
    parallelName: (color: string) => color,
    parallelCompany: "text-slate-500",
  },
}
